<div class="row pt-5">
   <div class="col-lg-2 text-center">
      <img src="../public/img/myAvatar.png" class="rounded-circle" alt="Avatar">
   </div>
   <div class="col-lg-10 text-center">
      <h2>zayna kaadan<br> étudiante développeur PHP / Symfony chez OpenClassrooms</h2>
   </div>
</div>
<h1> Homepage </h1>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur voluptatum deleniti aliquam, quasi repellendus quaerat neque delectus atque, expedita doloremque tempora ut asperiores architecto nemo provident nesciunt sint debitis. Incidunt mollitia porro magni a quod totam ad iste molestiae architecto tempora iusto delectus vero quidem vel modi minus laboriosam, adipisci officiis hic quibusdam. Ipsa, ex? Esse, veniam, excepturi numquam quos aliquam incidunt tempora accusantium alias dicta ducimus sapiente nam, unde rerum architecto velit animi possimus voluptatem ipsa. Expedita repellat magnam atque ducimus quam corrupti, architecto impedit? Asperiores, voluptatem nesciunt perspiciatis optio animi tempore modi praesentium laboriosam iusto at facere illum commodi maxime pariatur? Atque ipsum tenetur iusto officiis voluptates, eius praesentium magnam. Quos rerum, eius distinctio soluta ad a amet? Deleniti tempore ullam iusto vero accusantium veritatis quo fuga quidem. Hic voluptates in nemo culpa? Dolor nemo odio illum, repellat recusandae modi dignissimos at. Consequatur harum natus cumque, esse veritatis fugit vitae in deleniti nam sunt, ipsam mollitia iste sed quia id. Molestias excepturi accusantium porro quae magni necessitatibus cupiditate omnis ducimus hic vitae maiores vero magnam, facere odit sunt unde? Quam fugiat consectetur dolorem veniam libero tempore veritatis mollitia non? Fugiat eum voluptates facilis maiores nesciunt nulla cum ad placeat rem, explicabo libero labore molestiae distinctio consequuntur minima a aspernatur voluptatem quae fugit quidem officia autem vitae quisquam? Incidunt excepturi qui dolore at soluta aliquam veniam odit, facere impedit, eligendi inventore itaque, neque alias suscipit fugit velit architecto esse asperiores. Tempora libero excepturi corporis cupiditate, laborum labore beatae. Obcaecati?</p>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur voluptatum deleniti aliquam, quasi repellendus quaerat neque delectus atque, expedita doloremque tempora ut asperiores architecto nemo provident nesciunt sint debitis. Incidunt mollitia porro magni a quod totam ad iste molestiae architecto tempora iusto delectus vero quidem vel modi minus laboriosam, adipisci officiis hic quibusdam. Ipsa, ex? Esse, veniam, excepturi numquam quos aliquam incidunt tempora accusantium alias dicta ducimus sapiente nam, unde rerum architecto velit animi possimus voluptatem ipsa. Expedita repellat magnam atque ducimus quam corrupti, architecto impedit? Asperiores, voluptatem nesciunt perspiciatis optio animi tempore modi praesentium laboriosam iusto at facere illum commodi maxime pariatur? Atque ipsum tenetur iusto officiis voluptates, eius praesentium magnam. Quos rerum, eius distinctio soluta ad a amet? Deleniti tempore ullam iusto vero accusantium veritatis quo fuga quidem. Hic voluptates in nemo culpa? Dolor nemo odio illum, repellat recusandae modi dignissimos at. Consequatur harum natus cumque, esse veritatis fugit vitae in deleniti nam sunt, ipsam mollitia iste sed quia id. Molestias excepturi accusantium porro quae magni necessitatibus cupiditate omnis ducimus hic vitae maiores vero magnam, facere odit sunt unde? Quam fugiat consectetur dolorem veniam libero tempore veritatis mollitia non? Fugiat eum voluptates facilis maiores nesciunt nulla cum ad placeat rem, explicabo libero labore molestiae distinctio consequuntur minima a aspernatur voluptatem quae fugit quidem officia autem vitae quisquam? Incidunt excepturi qui dolore at soluta aliquam veniam odit, facere impedit, eligendi inventore itaque, neque alias suscipit fugit velit architecto esse asperiores. Tempora libero excepturi corporis cupiditate, laborum labore beatae. Obcaecati?</p>
</div>
